media:
  input: assets/img
  output: /assets/img
content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    # subfolders: false
    filename: '{year}-{month}-{day}-{primary}.md'
    view: 
      fields: [title, draft, date]
      sort: [date, title, draft]
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: YYYY-MM-DDTHH:mm:ss Z
          step: 60
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: featured_image
        label: Featured image
        type: image
      - name: featured_image_alt
        label: Featured image alt text
        type: text
        options:
          rows: 3
      - name: excerpt
        label: Excerpt
        type: text
      - name: body
        label: Body
        type: rich-text
  - name: pages
    label: Pages
    path: src/pages
    type: collection
    view:
      fields: [title, slug]
      sort: [title, eleventyNavigation.order]
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - name: key
            label: Menu item
            type: string
          - name: order
            label: Order
            type: number
      - name: body
        label: Body
        type: rich-text