media:
  input: assets/img
  output: /assets/img
content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    view: 
      fields: [title, date, draft, tags]
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string

  - name: pages
    label: Pages
    path: src/pages
    type: collection
    fields: [title]
