title: seanlunsford.com
url: 'https://seanlunsford.com'
github_url: 'https://github.com/slunsford/seanlunsford.com'
author:
  name: Sean Lunsford
  email: sean@seanlunsford.com
  url: 'https://seanlunsford.com'
  mastodon_url: 'https://data-folks.masto.host/@sean'
  mastodon_handle: '@sean@data-folks.masto.host'
  blueksky_url: 'https://bsky.app/profile/seanlunsford.com'
  github_url: 'https://github.com/slunsford'
