title: seanlunsford.com
url: https://seanlunsford.com
github_url: https://github.com/slunsford/seanlunsford.com
opengraph_image: /assets/img/opengraph.png
author:
  name: Sean Lunsford
  email: sean@seanlunsford.com
  avatar: /assets/img/sean.png
  url: https://seanlunsford.com
  mastodon_url: https://mastodon.seanlunsford.com/@sean
  mastodon_handle: "@sean@seanlunsford.com"
  bluesky_url: https://bsky.app/profile/seanlunsford.com
  github_url: https://github.com/slunsford
