title: Global Variables
description: "Reflections by Sean Lunsford: analytics engineer; adult third culture kid; semi-stationary digital nomad, currently based in Dehradun, India"
url: https://seanlunsford.com
github_url: https://github.com/slunsford/seanlunsford.com
opengraph_image: /images/opengraph.png
author:
  name: Sean Lunsford
  email: sean@seanlunsford.com
  avatar: /images/sean.png
  url: https://seanlunsford.com
  mastodon_url: https://mastodon.seanlunsford.com/@sean
  mastodon_handle: "@sean@seanlunsford.com"
  bluesky_url: https://bsky.app/profile/seanlunsford.com
  github_url: https://github.com/slunsford
